
# Name of your site (displayed in the header)
name: Algony Tony

# Short bio or description (displayed in the header)
description: etvdyn

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /assets/img/sys/jekyll-logo.png

# Includes an icon in the footer for each username you enter
footer-links:
  rss: feed
  email: # txzhu1010@gmail.com
  github: # algony-tony
  twitter: # zhu_tony
  dribbble:
  facebook:
  flickr:
  instagram:
  linkedin:
  pinterest:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: https-algony-tony-github-io

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: G-QHD5V4HSLX

# Enter your Google Adsense client id
AdSense: ca-pub-3291441471504209

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://algony-tony.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

permalink: /:title/
timezone: Asia/Hong_Kong # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
locale: zh-CN
mathjax: false  # enables support for mathjax - set to 'false' to disable

defaults:
  -
    scope:
      path: "assets/file/*.pdf"
    values:
      sitemap: false

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
    css_class: 'highlight'
highlighter: rouge

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # :expanded

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - "script"
